name: Build and push image
run-name: Build and deploy image to AWS ECR.
on:
  push: 
    branches:
      - master
      - feature/Docker
permissions:
 id-token: write
 contents: read
env:
  AWS-ACCOUNT-ID: '056331603841'
  AWS-REGION: 'ap-southeast-2'
  IMAGE-NAME: 'mycoolwebapi'
  IMAGE-TAG: ${{ github.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS-ACCOUNT-ID }}:role/github_actions_role
          aws-region: ${{ env.AWS-REGION }}
          role-session-name: samplerolesession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 056331603841.dkr.ecr.ap-southeast-2.amazonaws.com/mycoolwebapi
          region: ${{ env.AWS-REGION }}

      - name: Build and tag Docker image
        run: |
          cd ./MyCoolWebAPI
          docker build -t ${{ env.IMAGE-NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE-NAME }}:${{ github.sha }} ${{ env.IMAGE-NAME }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.IMAGE-NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE-NAME }}:latest