name: Build and push project
on:
  push:
    branches:
    - '*'

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: '056331603841'
  AWS_REGION: 'ap-southeast-2'
  BUCKET_NAME: 'techfolio'

jobs:
  build-and-deploy-spa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_actions_role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: samplerolesession1
      - name: Build and deploy React App
        run: |
          ls
          cd _spa
          npm install && npm run build:production
      - name: Deploy app build to S3 bucket
        run: |
          cd _spa
          aws s3 sync ./build/ s3://${{ env.BUCKET_NAME }} --delete

  build-and-deploy-lambda:
      runs-on: ubuntu-latest
      steps:
        - name: Checking out code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_actions_role
            aws-region: ${{ env.AWS_REGION }}
            role-session-name: samplerolesession2
        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install boto3 contentful

        - name: Build deployment package
          run: |
            cd lambda
            mkdir package
            ls
            cp lambda_function.py package/
            cp -r ../venv/lib/python3.10/site-packages/* package/
            cd package
            zip -r ../../lambda_function.zip .

        - name: Deploy Lambda
          run: |
            ls
            aws lambda update-function-code --function-name techfolio-contentful --zip-file fileb://lambda_function.zip