name: Build and push image
run-name: Build and deploy image to AWS ECR.
on:
  push: 
    branches:
      - master
      - feature/Docker
permissions:
 id-token: write
 contents: read
env:
  AWS-ACCOUNT-ID: 056331603841
  AWS-REGION: 'ap-southeast-2'
  IMAGE-NAME: mycoolwebapi
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS-ACCOUNT-ID }}:role/github_actions_role
          aws-region: ${{ env.AWS-REGION }}
          role-session-name: samplerolesession

      - name: Build and push Docker image
        run: |
          docker build -t ${{env.IMAGE-NAME}} .
          docker tag ${{env.IMAGE-NAME}}:latest ${{ env.AWS-ACCOUNT-ID }}.dkr.ecr.${{ env.AWS-REGION }}.amazonaws.com/${{env.IMAGE-NAME}}:latest
          aws ecr get-login-password --region ${{ env.AWS-REGION }} | docker login --username AWS --password-stdin ${{ env.AWS-ACCOUNT-ID }}.dkr.ecr.${{ env.AWS-REGION }}.amazonaws.com
          docker push ${{ env.AWS-ACCOUNT-ID }}.dkr.ecr.${{ env.AWS-REGION }}.amazonaws.com/${{env.IMAGE-NAME}}:latest
