name: Build and push image
run-name: Build and deploy image to AWS ECR.
on:
  push:
    branches:
      - '*'
  pull_request:
permissions:
  id-token: write
  contents: read
env:
  AWS_ACCOUNT_ID: '056331603841'
  AWS_REGION: 'ap-southeast-2'
  IMAGE_NAME: 'bff'
  IMAGE_TAG: ${{ github.sha }}
  ECR_REPOSITORY: 'bff' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          ls
          cd ./_bff 
          docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: _bff
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_actions_role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: samplerolesession

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: _bff

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}
          region: ${{ env.AWS_REGION }}

      - name: Load Docker image
        run: |
          ls _bff
          docker load -i _bff/bff.tar

      - name: Tag Docker image
        run: |
          docker tag ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest